### ISSUE TITLE
Region-specific build failure: Chicago

### ISSUE THREAD

**Issue by demory** [opentripplanner/OTPSetup#10]
A deployer request (#41) for Chicago failed with the following issue(s):
- CSV reader failure when reading GTFS

Graph builder output on S3:
otp-graphs/output/req41_2012-04-03-16:46:00_output.txt

Graph builder data inputs tarball on S3:
otp-graphs/data/req41_2012-04-03-16:46:00.tar.gz

Relevant stack trace / JRE output:
Exception in thread "main" org.onebusaway.csv_entities.exceptions.CsvEntityIOException: io error: entityType=org.onebusaway.gtfs.model.Trip path=java.io.InputStreamReader@572128ed lineNumber=2063
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:157)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:116)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:111)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:104)
    at org.opentripplanner.graph_builder.impl.GtfsGraphBuilderImpl.loadBundle(GtfsGraphBuilderImpl.java:191)
    at org.opentripplanner.graph_builder.impl.GtfsGraphBuilderImpl.buildGraph(GtfsGraphBuilderImpl.java:125)
    at org.opentripplanner.graph_builder.GraphBuilderTask.run(GraphBuilderTask.java:135)
    at org.opentripplanner.graph_builder.GraphBuilderMain.main(GraphBuilderMain.java:49)
Caused by: java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
    at java.util.ArrayList.rangeCheck(ArrayList.java:571)
    at java.util.ArrayList.get(ArrayList.java:349)
    at org.onebusaway.csv_entities.IndividualCsvEntityReader.readEntity(IndividualCsvEntityReader.java:123)
    at org.onebusaway.csv_entities.IndividualCsvEntityReader.handleLine(IndividualCsvEntityReader.java:96)
    at org.onebusaway.csv_entities.CsvEntityReader.readEntities(CsvEntityReader.java:153)
    ... 7 more

**Comment by novalis** [comment]
I mentioned this in email, but the problem is bad GTFS:
38584,1956755,32,0,299056,SHUTTLE BUG TO BAXTER, PKWAY & SIEMENS
