### ISSUE TITLE
Region-specific build failure: Washington DC

### ISSUE THREAD

**Issue by demory** [opentripplanner/OTPSetup#12]
<i>Update: seg fault issue fixed w/ upgrade jvm 7. Now seeing same NED-related issue as ticket #11</i>

A deployer request (#42) for Washington DC failed with the following issue(s):
- NED-enabled graph builder failure (see https://github.com/openplans/OpenTripPlanner/issues/670)
- GTFS issues: numerous Zero-distance hop, Excessive speed, and GeometryChecker warnings

Graph builder output on S3:
otp-graphs/output/req44_2012-04-04-02:30:15_output.txt

Graph builder data inputs tarball on S3:
otp-graphs/data/req44_2012-04-04-02:30:15.tar.gz

Relevant stack trace / JRE output:
Exception in thread "main" java.lang.IllegalStateException: java.lang.NullPointerException
    at org.opentripplanner.graph_builder.GraphBuilderTask.run(GraphBuilderTask.java:126)
    at org.opentripplanner.graph_builder.GraphBuilderMain.main(GraphBuilderMain.java:49)
Caused by: java.lang.NullPointerException
    at org.opentripplanner.routing.edgetype.PlainStreetEdge.hashCode(PlainStreetEdge.java:415)
    at java.util.HashMap.put(HashMap.java:389)
    at org.opentripplanner.routing.graph.Graph.renumberVerticesAndEdges(Graph.java:264)
    at org.opentripplanner.routing.graph.Graph.save(Graph.java:368)
    at org.opentripplanner.graph_builder.GraphBuilderTask.run(GraphBuilderTask.java:124)
    ... 1 more

**Comment by novalis** [comment]
My only suggestion here is to upgrade the JVM

**Comment by demory** [comment]
Yep, upgrading to JRE 7 fixed the segfault. Now seeing the same NED-related issue as the others.
